export const data = {
  login: "singhguri",
  id: 61290735,
  node_id: "MDQ6VXNlcjYxMjkwNzM1",
  avatar_url: "https://avatars.githubusercontent.com/u/61290735?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/singhguri",
  html_url: "https://github.com/singhguri",
  followers_url: "https://api.github.com/users/singhguri/followers",
  following_url:
    "https://api.github.com/users/singhguri/following{/other_user}",
  gists_url: "https://api.github.com/users/singhguri/gists{/gist_id}",
  starred_url: "https://api.github.com/users/singhguri/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/singhguri/subscriptions",
  organizations_url: "https://api.github.com/users/singhguri/orgs",
  repos_url: "https://api.github.com/users/singhguri/repos",
  events_url: "https://api.github.com/users/singhguri/events{/privacy}",
  received_events_url: "https://api.github.com/users/singhguri/received_events",
  type: "User",
  site_admin: false,
  name: "Gurpreet Singh",
  company: null,
  blog: "",
  location: "Chandigarh",
  email: null,
  hireable: null,
  bio: "In a World Full of People Craving for materialistic things ... I am searching for something to fulfill my hunger for knowledge.",
  twitter_username: null,
  public_repos: 23,
  public_gists: 0,
  followers: 0,
  following: 4,
  created_at: "2020-02-20T18:24:31Z",
  updated_at: "2022-02-25T04:52:28Z",
};
